### PR TITLE
Clamp min emit time to 0.001

### LINKED ISSUE #257: Particle emit time near zero causes freeze
Steps to reproduce:
Create an entity in a scene.
Add particle emitter component to emitter.
Set emit time close to zero.
Try to run scene.
This will cause the editor to freeze.

### PR DESCRIPTION
**Pull request by LarsIngo**
Fixes #257

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ParticleManager.cpp#L59](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/f7e59a9f63e3d16ecf84b202cd98af866a7e3156/src/Engine/Manager/ParticleManager.cpp#L59): The function 'UpdateBuffer' is never used. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedFunction)
1. ![INFO][INFO] [EntityEditor.cpp#L443](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/f7e59a9f63e3d16ecf84b202cd98af866a7e3156/src/Editor/GUI/Editors/EntityEditor.cpp#L443): keyword 'if' not followed by a single space [rule](http://localhost:9000/coding_rules#rule_key=vera%2B%2B%3AT008)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by andens** [comment]
iamheman

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ParticleManager.cpp#L59](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/130a84ff32e8ea8a205c767dceb3b0853cd69acc/src/Engine/Manager/ParticleManager.cpp#L59): The function 'UpdateBuffer' is never used. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedFunction)
1. ![INFO][INFO] [EntityEditor.cpp#L443](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/130a84ff32e8ea8a205c767dceb3b0853cd69acc/src/Editor/GUI/Editors/EntityEditor.cpp#L443): keyword 'if' not followed by a single space [rule](http://localhost:9000/coding_rules#rule_key=vera%2B%2B%3AT008)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ParticleManager.cpp#L59](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/425e1b0133a344dcb95a574f251919b99ca941bd/src/Engine/Manager/ParticleManager.cpp#L59): The function 'UpdateBuffer' is never used. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedFunction)
1. ![INFO][INFO] [EntityEditor.cpp#L443](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/425e1b0133a344dcb95a574f251919b99ca941bd/src/Editor/GUI/Editors/EntityEditor.cpp#L443): keyword 'if' not followed by a single space [rule](http://localhost:9000/coding_rules#rule_key=vera%2B%2B%3AT008)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
